# Generated by Django 4.2.16 on 2026-06-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='game',
            field=models.CharField(choices=[('bubble', 'Bubble Shooter'), ('candy', 'Candy Crush')], default='bubble', max_length=20),
        ),
    ]
