# Generated by Django 4.2.16 on 2026-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_scoreboard_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='game',
            field=models.CharField(choices=[('bubble', 'Bubble Shooter'), ('candy', 'Candy Crush'), ('snake', 'Snake'), ('flappy', 'Flappy Bird'), ('memory', 'Memory Match'), ('whack', 'Whack-a-Mole')], default='bubble', max_length=20),
        ),
    ]
