# Generated by Django 4.2.16 on 2026-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_scoreboard_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='game',
            field=models.CharField(choices=[('candy', 'Candy Crush'), ('snake', 'Snake'), ('flappy', 'Flappy Bird'), ('memory', 'Memory Match'), ('whack', 'Whack-a-Mole')], default='candy', max_length=20),
        ),
    ]
